### ISSUE TITLE
Discussion on nodestore Solutions

### ISSUE THREAD

**Issue by klboke** [andrsp/sentry-nodestore-elastic#1]
> https://github.com/getsentry/self-hosted/issues/1808#issuecomment-2292907523

We found that nodestore is a typical KV model, so the value itself does not require any structure. Using an object storage product like S3 might be more suitable than using Elasticsearch.

**Comment by andrsp** [comment]
Agree, it depends on what kind of infrastructure you run Sentry on premise and which tools you have in place and has knowledge about :)
